---
- name: Install rsyslog and rsyslog-module-gtls
  ansible.builtin.package:
    name:
      - "rsyslog>=8.2306"
      - "rsyslog-module-gtls>=8.2306"
    state: present
  changed_when: true

- name: Start service rsyslog and enable it
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
  changed_when: true
